const strings = {
	accounts: "Аккаунты",
	active: "Активен",
	add: "Добавить",
	admin: "Администратор",
	administration: "Администрирование",
	block: "Заблокировать",
	blocking: "Блокировка",
	cancel: "Отмена",
	change_password: "Изменить пароль",
	confirm: "Подтвердить",
	confirm_new_password: "Подтверждение нового пароля",
	confirm_password: "Подтверждение пароля",
	create: "Создать",
	create_user: "Создать пользователя",
	delete_image: "Удалить изображение",
	department: "Отдел",
	description: "Описание",
	do_you_really_want_to_block_user_: "Вы действительно хотите заблокировать пользователя ",
	do_you_really_want_to_unblock_user_: "Вы действительно хотите разблокировать пользователя ",
	drag_n_drop_file_or_click_and_select: "Перетащите файлы сюда, или нажмите для выбора файла",
	edit: "Редактировать",
	email: "Email",
	email_not_valid: "Email не валиден",
	filter: "Фильтровать",
	filters: "Фильтры",
	find: "Найти",
	first_name: "Имя",
	for_stuff: "Для сотрудников",
	full_name: "Ф.И.О.",
	go_back_home: "Вернуться на главную",
	groups: "Группы",
	home_page: "Главная",
	id: "ID",
	last_login: "Последний вход",
	last_name: "Фамилия",
	logout: "Выход",
	manager: "Менеджер",
	middle_name: "Отчество",
	name: "Название",
	new_password: "Новый пароль",
	next: "Далее",
	no: "Нет",
	no_image: "Нет изображения",
	old_password: "Старый пароль",
	operations: "Операции",
	page_error: "На странице что-то произошло не так...",
	page_not_found: "Страница не найдена",
	password: "Пароль",
	password_reset_successfully: "Пароль успешно изменен",
	passwords_do_not_match: "Пароли не совпадают",
	phone: "Телефон",
	read: "Прочитано",
	reports: "Отчеты",
	required_field: "Обязательное поле",
	reset: "Сброс",
	reset_password: "Сбросить пароль",
	role: "Роль",
	search: "Поиск",
	sign_in: "Войти",
	sign_in_: "Вход",
	start: "Начать",
	status: "Статус",
	success: "Успешно",
	text: "Текст",
	title: "Заголовок",
	to: "До",
	type: "Тип",
	unable_to_fetch_: "Не удалось загрузить ",
	unable_to_load_image: "Не удалось загрузить изображение",
	unblock: "Разблокировать",
	unblocking: "Разблокировка",
	unknown_error: "Неизвестная ошибка",
	update_user: "Редактировать пользователя",
	upload_image: "Загрузить изображение",

	user: "Пользователь",
	user_successfully_blocked: "Пользователь успешно заблокирован",
	user_successfully_unblocked: "Пользователь успешно разблокирован",
	username: "Имя пользователя",
	value_copied: "Значение скопировано",
	yes: "Да",
};

export default strings;
